const DATA={biology:{title:'Biologi 2',modules:[
{id:'b1',title:'Liv, celler & arbetssätt',sub:'Moment 1',lead:'Vad är liv – och hur undersöker vi det?',focus:'Cellens grunder och naturvetenskaplig metod',concepts:[['Livets kännetecken','Organismer har celler, ämnesomsättning, reagerar på omgivningen och kan fortplanta sig.'],['Cellen','Cellmembran avgränsar cellen. DNA bär information och ribosomer bygger protein.'],['Naturvetenskap','Fråga → hypotes → metod → resultat → slutsats. Resultatet avgör om hypotesen får stöd.']],q:'Vad är skillnaden mellan en hypotes och en slutsats?',a:'En hypotes är en testbar förutsägelse före undersökningen. Slutsatsen skrivs efteråt och bygger på resultatet.'},
{id:'b2',title:'Ekologi & miljö',sub:'Moment 2 · examination',lead:'Allt i naturen hänger ihop',focus:'Kretslopp, miljöhot och hållbar utveckling',concepts:[['Kretslopp','Kol, kväve och vatten cirkulerar mellan organismer och miljö. Energi flödar däremot genom systemet.'],['Näringskedja','Producent → konsument → toppkonsument. Energi förloras som värme i varje led.'],['Miljöhot','Övergödning, miljögifter och klimatförändring påverkar hela ekosystem.']],q:'Varför blir mängden energi mindre högre upp i en näringskedja?',a:'Organismer använder mycket energi till livsprocesser och den lämnar systemet som värme. Bara en del binds i biomassa och går vidare.'},
{id:'b3',title:'Systematik & organismer',sub:'Moment 2 · examination',lead:'Sortera liv efter släktskap',focus:'Prokaryoter, eukaryoter, svampar, växter och djur',concepts:[['Prokaryot','Saknar cellkärna. Bakterier och arkéer är prokaryoter.'],['Eukaryot','Har cellkärna och membranbundna organeller.'],['Evolutionärt släktskap','Modern systematik grupperar organismer efter gemensamt ursprung, inte bara utseende.']],q:'Vilken huvudskillnad skiljer prokaryota och eukaryota celler?',a:'Eukaryota celler har cellkärna och membranbundna organeller. Prokaryota celler saknar cellkärna.'},
{id:'b4',title:'Celler & energi',sub:'Moment 3',lead:'Så får och använder cellen energi',focus:'Cellandning, fotosyntes och organeller',concepts:[['Cellandning','Glukos + syre → koldioxid + vatten + användbar energi (ATP).'],['Fotosyntes','Koldioxid + vatten + ljusenergi → glukos + syre.'],['Sambandet','Fotosyntesen lagrar solenergi i glukos. Cellandningen frigör energin.']],q:'Hur hänger fotosyntes och cellandning ihop?',a:'Fotosyntesen bygger glukos och syre av koldioxid och vatten. Cellandningen använder glukos och syre och bildar koldioxid och vatten.'},
{id:'b5',title:'Genteknik & osmos',sub:'Moment 3 · övning/labb',lead:'DNA kan undersökas och förändras',focus:'Genteknikens grunder samt transport över membran',concepts:[['Gen','Ett avsnitt DNA med information som kan ge en funktionell produkt, ofta ett protein.'],['Genteknik','Metoder för att läsa, kopiera eller förändra DNA. Nytta och risker måste värderas.'],['Osmos','Vatten rör sig genom ett halvgenomsläppligt membran mot sidan med högre koncentration lösta ämnen.']],q:'Vad händer med en cell i en lösning med högre koncentration lösta ämnen utanför cellen?',a:'Vatten lämnar cellen genom osmos, så cellen krymper.'}]},physics:{title:'Fysik 1a1',modules:[
{id:'p1',title:'Mätning & problemlösning',sub:'Moment 1 · diagnostiskt prov',lead:'Fysik börjar med mätbara storheter',focus:'Enheter, värdesiffror och metod',concepts:[['Storhet','Något mätbart, till exempel längd, tid, massa eller kraft.'],['SI-enhet','Gemensamma grundenheter: meter, sekund och kilogram.'],['Omvandling','Gör alltid enheterna kompatibla innan du räknar. 1 m/s = 3,6 km/h.']],q:'Varför måste 72 km/h omvandlas innan du använder sekunder och meter?',a:'Formlerna kräver kompatibla enheter. 72 km/h ÷ 3,6 = 20 m/s.'},
{id:'p2',title:'Rörelse & krafter',sub:'Moment 2 · diagnostiskt prov',lead:'Beskriv hur rörelsen förändras',focus:'Hastighet, acceleration, Newton och friktion',concepts:[['Hastighet','v = s/t. Berättar hur snabbt läget ändras.'],['Acceleration','a = Δv/Δt. Berättar hur snabbt hastigheten ändras.'],['Newtons andra lag','F = m·a. En resulterande kraft ger acceleration.']],q:'En kraft på 20 N verkar på massan 10 kg. Vilken acceleration får den?',a:'a = F/m = 20/10 = 2 m/s².'},
{id:'p3',title:'Densitet, tryck & lyftkraft',sub:'Moment 3',lead:'Krafter fördelade över ytor och volymer',focus:'ρ = m/V, p = F/A och Arkimedes princip',concepts:[['Densitet','ρ = m/V. Stor massa i liten volym ger hög densitet.'],['Tryck','p = F/A. Samma kraft på mindre yta ger större tryck.'],['Lyftkraft','Ett föremål i vätska påverkas uppåt av tyngden hos undanträngd vätska.']],q:'Varför ger en spetsig sko högre tryck än en platt sko vid samma kroppsvikt?',a:'Kraften är samma men arean mindre. Eftersom p = F/A blir trycket större.'},
{id:'p4',title:'Energi & effekt',sub:'Moment 4',lead:'Energi försvinner inte – den omvandlas',focus:'Lägesenergi, rörelseenergi, effekt och verkningsgrad',concepts:[['Lägesenergi','Eₚ = mgh. Beror på massa, höjd och tyngdacceleration.'],['Rörelseenergi','Eₖ = mv²/2. Hastigheten påverkar i kvadrat.'],['Effekt','P = E/t. Hur snabbt energi omsätts.']],q:'Vad händer med rörelseenergin om hastigheten fördubblas?',a:'Den blir fyra gånger så stor eftersom hastigheten är i kvadrat: (2v)² = 4v².'},
{id:'p5',title:'Jämvikt, moment & impuls',sub:'Moment 5 · prov 1–5',lead:'Krafter kan vrida och rörelsemängd kan ändras',focus:'Komposanter, vridmoment, rörelsemängd och impuls',concepts:[['Vridmoment','M = F·l. Kraft gånger vinkelrätt avstånd till vridpunkten.'],['Rörelsemängd','p = m·v. Beror på massa och hastighet.'],['Impuls','I = F·Δt = Δp. Kraft under tid ändrar rörelsemängden.']],q:'Hur kan en längre skiftnyckel göra det lättare att lossa en mutter?',a:'Avståndet till vridpunkten ökar. Då ger samma kraft ett större vridmoment M = F·l.'},
{id:'p6',title:'Laddning & elektriska fält',sub:'Moment 6',lead:'Laddningar påverkar varandra på avstånd',focus:'Laddning, Coulombs kraft, fält och spänning',concepts:[['Laddning','Lika laddningar repellerar, olika attraherar.'],['Elektriskt fält','Beskriver kraftverkan på en positiv provladdning i varje punkt.'],['Spänning','Energi per laddning: U = E/Q. Mäts i volt.']],q:'Vad betyder elektrisk spänning med enkla ord?',a:'Hur mycket elektrisk energi varje coulomb laddning kan få eller avge.'},
{id:'p7',title:'Ström & kretsar',sub:'Moment 7 · labb',lead:'Laddning i rörelse',focus:'I = Q/t, Ohms lag och serie/parallell',concepts:[['Ström','I = Q/t. Laddning som passerar per sekund.'],['Ohms lag','U = R·I. Kopplar ihop spänning, resistans och ström.'],['Kopplingar','I serie är strömmen samma. Parallellgrenar har samma spänning.']],q:'En resistor på 10 Ω kopplas till 5 V. Hur stor blir strömmen?',a:'I = U/R = 5/10 = 0,5 A.'},
{id:'p8',title:'Värme & faser',sub:'Moment 8 · slutprov',lead:'Partiklarnas rörelse förklarar värme',focus:'Inre energi, temperatur, uppvärmning och fasövergångar',concepts:[['Temperatur','Mått på partiklarnas genomsnittliga rörelseenergi.'],['Värme','Energi som överförs på grund av temperaturskillnad.'],['Fasövergång','Under smältning/kokning används energi till att ändra bindningar; temperaturen kan vara konstant.']],q:'Varför kan temperaturen vara konstant medan vatten kokar?',a:'Den tillförda energin används till fasövergången och att separera partiklar, inte till att öka deras genomsnittliga rörelseenergi.'}]}};
const kind=document.body.dataset.course,data=DATA[kind],key='study-'+kind,state={module:data.modules[0].id,scores:JSON.parse(localStorage.getItem(key)||'{}')};
const nav=document.getElementById('moduleNav'),view=document.getElementById('view'),crumb=document.getElementById('crumb');
function save(){localStorage.setItem(key,JSON.stringify(state.scores));progress()}
function progress(){const vals=Object.values(state.scores),green=vals.filter(x=>x==='green').length,pct=Math.round(green/data.modules.length*100);document.getElementById('progressText').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%'}
function renderNav(){nav.innerHTML=data.modules.map(m=>`<button class="mod-btn ${m.id===state.module?'active':''}" data-id="${m.id}">${state.scores[m.id]==='green'?'🟢 ':state.scores[m.id]==='yellow'?'🟡 ':state.scores[m.id]==='red'?'🔴 ':''}${m.title}<small>${m.sub}</small></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.module=b.dataset.id;renderNav();render();document.getElementById('side').classList.remove('open')})}
function render(){const m=data.modules.find(x=>x.id===state.module);crumb.textContent=m.title;const physics=kind==='physics';view.innerHTML=`<div class="hero"><div class="hero-card"><span class="eyebrow">${m.sub}</span><h1>${m.lead}</h1><p>Fokusera på sambandet och förklara det med egna ord. Det räcker att du kan kärnan stabilt på E-nivå.</p></div><div class="focus"><small>DETTA SKA SITTA</small><strong>${m.focus}</strong><span>Lär → tänk → active recall → bedöm → repetera.</span></div></div><div class="section"><h2>E-kärnan</h2><div class="grid">${m.concepts.map(c=>`<article class="card"><span class="tag">VIKTIGT</span><h3>${c[0]}</h3><p>${c[1]}</p></article>`).join('')}</div></div>${physics?`<div class="section"><h2>Metoden vid beräkningar</h2><div class="problem"><div class="steps"><div>Vad vet vi?</div><div>Vad söker vi?</div><div>Välj formel</div><div>Kontrollera och omvandla enheter</div><div>Sätt in, räkna och skriv rätt enhet</div><div>Rimlighetskontroll</div></div></div></div>`:''}<div class="section"><h2>Active recall</h2><div class="recall"><span class="tag">SVARA HÖGT FÖRST</span><p class="question">${m.q}</p><button class="reveal">Visa förklaring</button><div class="answer">${m.a}</div><div class="ratings"><button class="rate" data-v="green">🟢 Sitter</button><button class="rate" data-v="yellow">🟡 Delvis</button><button class="rate" data-v="red">🔴 Sitter inte</button></div></div></div>`;const reveal=view.querySelector('.reveal'),answer=view.querySelector('.answer'),ratings=view.querySelector('.ratings');reveal.onclick=()=>{answer.classList.add('show');ratings.classList.add('show');reveal.textContent='Förklaringen visas'};view.querySelectorAll('.rate').forEach(b=>{if(state.scores[m.id]===b.dataset.v)b.classList.add('selected');b.onclick=()=>{state.scores[m.id]=b.dataset.v;save();renderNav();view.querySelectorAll('.rate').forEach(x=>x.classList.toggle('selected',x===b))}})}
document.getElementById('menuBtn').onclick=()=>document.getElementById('side').classList.toggle('open');document.getElementById('resetBtn').onclick=()=>{if(confirm('Nollställa din kunskapsbank?')){state.scores={};save();renderNav();render()}};renderNav();render();progress();
